development:
  adapter: postgresql
  encoding: unicode
  database: dayjot_development
  pool: 5
  username: Marc
  password:
test:
  adapter: postgresql
  database: dayjot_test
  username: Marc
  password:
